### ISSUE TITLE
Error: No links found

### ISSUE THREAD

**Issue by wangyesong11** [henryleeworld/laravel-youtube-downloader#1]
I tried to see if the link worked, and it definitely did

**Comment by henryleeworld** [comment]
@wangyesong11 Would you mind using the link "https://www.youtube.com/watch?v=-2X4dIyaxxU" to test whether the download feature is working as expected?

**Comment by henryleeworld** [comment]
@wangyesong11 It looks like the package has been reported with the same issue from April 25th. I will see if there's any solution available, thanks for your report.
The issue link: https://github.com/Athlon1600/youtube-downloader/issues/172

**Comment by henryleeworld** [comment]
@wangyesong11 I updated the latest commit which can solve the package's issue, please use the latest version to try the feature again. Thanks.
